# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ddfdf98cee5295893bf545ec06593246a83cab422e42d51fc9b4b2c631889ea1fc483ab49cade1c449c258ad2b37721ffe8a98ac77c0b10df768c87307a56c1

test:
  secret_key_base: 7c457714f6400134dfd8b0f57732876d5daf038f210744284150a716a706ec6236c53dcbdca7f97930c4ddf90164b29c619bcbcf4d3b09b8865d4fac4c02c6dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
